version: '3'

services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password

    redis:
        image: 'redis:latest'

    #server:
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        # For automatic updated on change
        volumes:
            # don't override node_modules folder
            - /app/node_modules
            # map the server file to app
            - ./server:/app
        # Environment variables, that gets set up when the container is ran
        environment:
            - REDIS_HOST=redis
            # default port used by redis (docker hub)
            - REDIS_PORT=6379
            # default values used by postgres (docker hub)
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432

    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
        environment:
            - WDS_SOCKET_PORT=0

    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app
        # Without it: For index I calculated Nothing yet
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379

    # Watch for incoming requests and route them to the correct server
    # https://hub.docker.com/_/nginx
    nginx:
        # Without it: Nginx connect() failed
        depends_on:
            - api
            - client
        # no matter what, nginx should be running
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            # 3050 is the port on our machine
            - '3050:80'
